// Pre-compile the demo bundle into a committed `bundle.js` that defines
// `window.PATTER_BUNDLE`, so index.html plays it by just opening the file - no
// dev server, no module loader (matching the Patterplay drop-in story). Workspace
// packages resolve to their TS source via aliases (same as examples/player).

import * as esbuild from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

const res = await esbuild.build({
  entryPoints: [here("./gen-entry.ts")],
  bundle: true,
  format: "esm",
  platform: "node",
  write: false,
  alias: {
    "@patterkit/compiler": here("../../packages/compiler/src/index.ts"),
    "@patterkit/runtime": here("../../packages/runtime/src/index.ts"),
    "@patterkit/dialect": here("../../packages/dialect/src/index.ts"),
    "@patterkit/model": here("../../packages/model/src/index.ts"),
    "@patterkit/core": here("../../packages/core/src/index.ts"),
    "@wildwinter/expr": here("../../../expr/packages/expr/src/index.ts"),
    "@wildwinter/scoperegistry": here("../../../expr/packages/scoperegistry/src/index.ts"),
  },
});

const code = res.outputFiles[0].text;
const mod = await import("data:text/javascript;base64," + Buffer.from(code).toString("base64"));
writeFileSync(here("./bundle.js"), `// Generated by gen.mjs - the demo story compiled to a Patter bundle.\nwindow.PATTER_BUNDLE = ${JSON.stringify(mod.bundle, null, 2)};\n`);
console.log("wrote examples/drop-in/bundle.js");
