// The preload bridge: the ONLY channel between the renderer and the main process. It exposes a tiny,
// explicit `window.patter` API (shared/api.ts) over contextBridge - no Node, no fs, no ipcRenderer
// leaked to the page. Each method is a typed wrapper over one ipcMain.handle channel.

import { contextBridge, ipcRenderer } from "electron";
import type { PatterApi, PatterPlayApi, PatterSearchApi, PatterCoverageApi, PlayChoiceOption, SearchEntry, SearchMode, OpenResult, UpdaterPromptOptions } from "../shared/api.js";

const api: PatterApi = {
  boot: () => ipcRenderer.invoke("project:boot"),
  appReady: () => ipcRenderer.send("app:ready"),
  hydrate: () => ipcRenderer.invoke("project:hydrate"),
  openDialog: () => ipcRenderer.invoke("project:openDialog"),
  saveAs: () => ipcRenderer.invoke("project:saveAs"),
  openPath: (path) => ipcRenderer.invoke("project:openPath", path),
  createDialog: (name, vcs, buildBundle) => ipcRenderer.invoke("project:createDialog", name, vcs, buildBundle),
  forget: (path) => ipcRenderer.invoke("project:forget", path),
  readScene: (sceneId) => ipcRenderer.invoke("scene:read", sceneId),
  saveScene: (sceneId, flow, loc) => ipcRenderer.invoke("scene:save", sceneId, flow, loc),
  vcStatus: () => ipcRenderer.invoke("project:vcStatus"),
  readDocs: (sceneId) => ipcRenderer.invoke("scene:readDocs", sceneId),
  saveDocs: (sceneId, map) => ipcRenderer.invoke("scene:saveDocs", sceneId, map),
  readComments: (sceneId) => ipcRenderer.invoke("scene:readComments", sceneId),
  saveComments: (sceneId, comments) => ipcRenderer.invoke("scene:saveComments", sceneId, comments),
  readWriting: (sceneId) => ipcRenderer.invoke("scene:readWriting", sceneId),
  saveWriting: (sceneId, map) => ipcRenderer.invoke("scene:saveWriting", sceneId, map),
  readRecording: (sceneId) => ipcRenderer.invoke("scene:readRecording", sceneId),
  saveRecording: (sceneId, map) => ipcRenderer.invoke("scene:saveRecording", sceneId, map),
  audioCurrent: () => ipcRenderer.invoke("audio:current"),
  onAudioIndex: (handler) => { ipcRenderer.on("audio:index", (_e, snap: Record<string, { status: string; path: string }>) => handler(snap)); },
  readAudio: (beatId) => ipcRenderer.invoke("audio:read", beatId),
  saveScratch: (beatId, bytes) => ipcRenderer.invoke("audio:saveScratch", beatId, bytes),
  setRecordingMode: (on) => { void ipcRenderer.invoke("recording:setMode", on); },
  debugStart: () => ipcRenderer.invoke("debug:start"),
  debugStop: () => ipcRenderer.invoke("debug:stop"),
  debugStatus: () => ipcRenderer.invoke("debug:status"),
  debugFollow: (flowId) => { void ipcRenderer.invoke("debug:follow", flowId); },
  onDebugStatus: (handler) => { ipcRenderer.on("debug:status", (_e, status: import("../shared/api.js").DebugStatus) => handler(status)); },
  readSuggestions: (sceneId) => ipcRenderer.invoke("scene:readSuggestions", sceneId),
  saveSuggestions: (sceneId, suggestions) => ipcRenderer.invoke("scene:saveSuggestions", sceneId, suggestions),
  reviewFeedback: (scope) => ipcRenderer.invoke("review:feedback", scope),
  listDictionaries: () => ipcRenderer.invoke("dict:list"),
  readDictionary: (id) => ipcRenderer.invoke("dict:read", id),
  importDictionary: () => ipcRenderer.invoke("dict:import"),
  removeDictionary: (id) => ipcRenderer.invoke("dict:remove", id),
  addDictionaryWord: (word) => ipcRenderer.invoke("dict:addWord", word),
  addIgnoreWord: (word) => ipcRenderer.invoke("dict:addIgnore", word),
  setDictionary: (patch) => ipcRenderer.invoke("dict:set", patch),
  report: () => ipcRenderer.invoke("project:report"),
  runCoverage: (options) => ipcRenderer.invoke("project:coverage", options),
  proposeCoverageDrivers: () => ipcRenderer.invoke("project:proposeCoverageDrivers"),
  exportReport: () => ipcRenderer.invoke("project:exportReport"),
  buildBundle: () => ipcRenderer.invoke("project:build"),
  buildAudioManifest: () => ipcRenderer.invoke("project:audioManifest"),
  exportVoiceScript: (everything) => ipcRenderer.invoke("project:exportVoiceScript", everything),
  exportPlayableHtml: () => ipcRenderer.invoke("project:exportPlayableHtml"),
  exportWeb: () => ipcRenderer.invoke("project:exportWeb"),
  exportScript: () => ipcRenderer.invoke("project:exportScript"),
  exportLoc: (request) => ipcRenderer.invoke("project:exportLoc", request),
  importLoc: (fallbackLocale) => ipcRenderer.invoke("project:importLoc", fallbackLocale),
  readSettings: () => ipcRenderer.invoke("project:readSettings"),
  saveSettings: (settings) => ipcRenderer.invoke("project:saveSettings", settings),
  setStart: (start) => ipcRenderer.invoke("project:setStart", start),
  reorderScenes: (ids) => ipcRenderer.invoke("project:reorderScenes", ids),
  createScene: (name) => ipcRenderer.invoke("project:createScene", name),
  sceneDeleteInfo: (sceneId) => ipcRenderer.invoke("project:sceneDeleteInfo", sceneId),
  deleteScene: (sceneId) => ipcRenderer.invoke("project:deleteScene", sceneId),
  rememberScene: (projectPath, sceneId, caretId) => ipcRenderer.invoke("scene:remember", projectPath, sceneId, caretId),
  openPlay: (sceneId, blockId) => ipcRenderer.invoke("play:open", sceneId, blockId),
  resetWindows: () => ipcRenderer.invoke("view:resetWindows"),
  playEdited: (sceneId, flow, loc) => { void ipcRenderer.invoke("play:edited", sceneId, flow, loc); },
  onPlayMark: (handler) => { ipcRenderer.on("play:mark", (_e, id: string | null, sceneId?: string) => handler(id, sceneId)); },
  onPlayReset: (handler) => { ipcRenderer.on("play:reset", () => handler()); },
  validate: (live) => ipcRenderer.invoke("project:validate", live),
  openSearchWindow: (mode, focus, query) => ipcRenderer.invoke("search:open", mode, focus, query),
  onSearchNavigate: (handler) => { ipcRenderer.on("search:navigate", (_e, entry: SearchEntry) => handler(entry)); },
  // Project-wide Replace coordination: main asks the editor to flush its open scene before applying, and
  // tells it to reload after. (The Replace UI itself lives in the search window: see searchApi below.)
  onEditorFlush: (handler) => { ipcRenderer.on("editor:flush", () => handler()); },
  editorFlushed: () => { void ipcRenderer.invoke("editor:flushed"); },
  onReplaceApplied: (handler) => { ipcRenderer.on("replace:applied", () => handler()); },
  openCoverageWindow: () => ipcRenderer.invoke("coverage:open"),
  onCoverageNavigate: (handler) => { ipcRenderer.on("coverage:navigate", (_e, sceneId: string, beatId: string) => handler(sceneId, beatId)); },
  onOpenWorldSettings: (handler) => { ipcRenderer.on("coverage:open-world", () => handler()); },
  applyFix: (fix) => ipcRenderer.invoke("project:applyFix", fix),
  getIdentity: () => ipcRenderer.invoke("identity:get"),
  setIdentity: (identity) => ipcRenderer.invoke("identity:set", identity),
  setPanes: (panes) => ipcRenderer.invoke("panes:set", panes),
  setTheme: (theme) => ipcRenderer.invoke("theme:set", theme),
  openExternal: (url) => { void ipcRenderer.invoke("app:openExternal", url); },
  onMenu: (handler) => { ipcRenderer.on("menu", (_e, cmd: string) => handler(cmd)); },
  onOpenProject: (handler) => { ipcRenderer.on("project:open", (_e, result: OpenResult) => handler(result)); },
  onUpdaterCheckDirty: (handler) => { ipcRenderer.on("updater:check-dirty", () => ipcRenderer.send("updater:dirty-reply", handler())); },
  onUpdaterSaveBeforeInstall: (handler) => { ipcRenderer.on("updater:save-before-install", () => { void handler().then((r) => ipcRenderer.send("updater:save-done", r)); }); },
  onUpdaterPrompt: (handler) => { ipcRenderer.on("updater:prompt", (_e, opts: UpdaterPromptOptions) => { void handler(opts).then((idx) => ipcRenderer.send("updater:prompt-reply", idx)); }); },
};

// The play window's bridge (drives the interactive walk + the editor step-marker).
const playApi: PatterPlayApi = {
  start: () => ipcRenderer.invoke("play:start"),
  step: () => ipcRenderer.invoke("play:step"),
  toStop: () => ipcRenderer.invoke("play:toStop"),
  choose: (optionId) => ipcRenderer.invoke("play:choose", optionId),
  mark: (beatId, sceneId) => { void ipcRenderer.invoke("play:markAt", beatId, sceneId); },
  resetMarks: () => { void ipcRenderer.invoke("play:resetMarks"); },
  onRestart: (handler) => { ipcRenderer.on("play:restart", () => handler()); },
  info: () => ipcRenderer.invoke("play:info"),
  audioBytes: (beatId) => ipcRenderer.invoke("audio:read", beatId),
  setPin: (on) => { void ipcRenderer.invoke("play:setPin", on); },
  setLocale: (locale) => ipcRenderer.invoke("play:setLocale", locale),
  setClosedCaptions: (on) => ipcRenderer.invoke("play:setCaptions", on),
  onStale: (handler) => { ipcRenderer.on("play:stale", () => handler()); },
  onRefreshed: (handler) => { ipcRenderer.on("play:refreshed", (_e, kind: "text" | "structure", options: PlayChoiceOption[]) => handler(kind, options)); },
};

// The detached search window's bridge (queries the project-wide index + drives the editor's jump).
const searchApi: PatterSearchApi = {
  info: () => ipcRenderer.invoke("searchWin:info"),
  search: (query) => ipcRenderer.invoke("searchWin:query", query),
  linesByStatus: (status, recording) => ipcRenderer.invoke("searchWin:byStatus", status, recording),
  propertyUsage: (query) => ipcRenderer.invoke("searchWin:byProperty", query),
  tagUsage: (tag) => ipcRenderer.invoke("searchWin:byTag", tag),
  tags: () => ipcRenderer.invoke("searchWin:tags"),
  statuses: (recording) => ipcRenderer.invoke("searchWin:statuses", recording),
  replacePreview: (opts) => ipcRenderer.invoke("searchWin:replacePreview", opts),
  replaceApply: (opts) => ipcRenderer.invoke("searchWin:replaceApply", opts),
  jump: (entry) => { void ipcRenderer.invoke("searchWin:jump", entry); },
  setPin: (on) => { void ipcRenderer.invoke("searchWin:setPin", on); },
  close: () => { void ipcRenderer.invoke("searchWin:close"); },
  onMode: (handler) => { ipcRenderer.on("searchWin:mode", (_e, mode: SearchMode) => handler(mode)); },
  onSeed: (handler) => { ipcRenderer.on("searchWin:seed", (_e, query: string) => handler(query)); },
  onProject: (handler) => { ipcRenderer.on("searchWin:project", () => handler()); },
};

// The detached coverage window's bridge (runs coverage in main; drives the editor's jump + External Properties tab).
const coverageApi: PatterCoverageApi = {
  info: () => ipcRenderer.invoke("covWin:info"),
  run: (options) => ipcRenderer.invoke("covWin:run", options),
  reveal: (sceneId, beatId) => { void ipcRenderer.invoke("covWin:reveal", sceneId, beatId); },
  openWorld: () => { void ipcRenderer.invoke("covWin:openWorld"); },
  findUsage: (ref) => { void ipcRenderer.invoke("covWin:findUsage", ref); },
  setPin: (on) => { void ipcRenderer.invoke("covWin:setPin", on); },
  onProject: (handler) => { ipcRenderer.on("covWin:project", () => handler()); },
};

contextBridge.exposeInMainWorld("patter", api);
contextBridge.exposeInMainWorld("patterPlay", playApi);
contextBridge.exposeInMainWorld("patterSearch", searchApi);
contextBridge.exposeInMainWorld("patterCoverage", coverageApi);
